language: python
dist: bionic
sudo: required

addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-dev
      - python3-setuptools

branches:
  except:
    - master

python:
  - "3.7"

stages:
  - pipeline

install:
  - pip3 install -r requirements.txt

jobs:
  include:
    - stage: pipeline
      name: "Pipeline process"
      script: python3 src/pipeline/main.py
